package app

import (
	"errors"
)

var ErrorMalformedTemplate = errors.New("A template is malformed.")
var ErrorMissingConfig = errors.New("Missing config environment variable.")
var ErrorCannotSendEmail = errors.New("Email dispatch failed. Please contact support to resolve this issue.")
var ErrorInternal = errors.New("An internal error has occurred. If you see this repeatedly, please contact support.")
var ErrorInvalidJSONBody = errors.New("Invalid JSON request. If you think this shouldn't happen, please contact support.")
var ErrorMissingField = errors.New("One or more field(s) empty.")
var ErrorEmailExists = errors.New("That email address is already registered. Sign in instead?")
var ErrorInvalidEmailPassword = errors.New("Invalid email/password combination.")
var ErrorUnconfirmedEmail = errors.New("Your email address is still unconfirmed. Please confirm your email address before proceeding.")
var ErrorNoSuchConfirmationToken = errors.New("This email confirmation link has expired.")
var ErrorNoSuchResetToken = errors.New("This password reset link has expired.")
var ErrorNotAuthorised = errors.New("You're not authorised to access that.")
var ErrorEmailAlreadyExists = errors.New("That email address has already been registered.")
var ErrorNoSuchToken = errors.New("No such session token.")
var ErrorNoSuchCommenter = errors.New("No such commenter.")
var ErrorAlreadyUpvoted = errors.New("You have already upvoted that comment.")
var ErrorNoSuchDomain = errors.New("This domain is not registered with Commento.")
var ErrorNoSuchComment = errors.New("No such comment.")
var ErrorInvalidState = errors.New("Invalid state value.")
var ErrorDomainFrozen = errors.New("Cannot add a new comment because that domain is frozen.")
var ErrorDomainAlreadyExists = errors.New("That domain has already been registered. Please contact support if you are the true owner.")
var ErrorUnauthorisedVote = errors.New("You need to be authenticated to vote.")
var ErrorNoSuchEmail = errors.New("No such email.")
var ErrorInvalidEmail = errors.New("You do not have an email registered with that account.")
var ErrorForbiddenEdit = errors.New("You cannot edit someone else's comment.")
var ErrorMissingSmtpAddress = errors.New("Missing SMTP_FROM_ADDRESS")
var ErrorSmtpNotConfigured = errors.New("SMTP is not configured.")
var ErrorOauthMisconfigured = errors.New("OAuth is misconfigured.")
var ErrorCannotReadResponse = errors.New("Cannot read response.")
var ErrorNotModerator = errors.New("You need to be a moderator to do that.")
var ErrorNotADirectory = errors.New("The given path is not a directory.")
var ErrorGzip = errors.New("Cannot GZip content.")
var ErrorCannotDownloadDisqus = errors.New("We could not download your Disqus export file.")
var ErrorCannotDownloadCommento = errors.New("We could not download your Commento export file.")
var ErrorSelfVote = errors.New("You cannot vote on your own comment.")
var ErrorInvalidConfigFile = errors.New("Invalid config file.")
var ErrorInvalidConfigValue = errors.New("Invalid config value.")
var ErrorNewOwnerForbidden = errors.New("New user registrations are forbidden and closed.")
var ErrorThreadLocked = errors.New("This thread is locked. You cannot add new comments.")
var ErrorDatabaseMigration = errors.New("Encountered error applying database migration.")
var ErrorNoSuchUnsubscribeSecretHex = errors.New("Invalid unsubscribe link.")
var ErrorEmptyPaths = errors.New("Empty paths field.")
var ErrorInvalidDomain = errors.New("Invalid domain name. Do not include the URL path after the forward slash.")
var ErrorInvalidEntity = errors.New("That entity does not exist.")
var ErrorCannotDeleteOwnerWithActiveDomains = errors.New("You cannot delete your account until all domains associated with your account are deleted.")
var ErrorNoSuchOwner = errors.New("No such owner.")
var ErrorCannotUpdateOauthProfile = errors.New("You cannot update the profile of an external account managed by third-party log in. Please use the appropriate platform to update your details.")
var ErrorUnsupportedCommentoImportVersion = errors.New("Unsupported Commento import format version.")
var ErrorInvalidAction = errors.New("Invalid action.")
var ErrorReservedName = errors.New("That name is reserved for deleted accounts! Please choose another.")
